# Generated by Django 5.1.7 on 2025-04-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_assigned_to_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('done', 'Tamamlandı')], default='pending', max_length=20),
        ),
    ]
