# Generated by Django 5.1.7 on 2025-04-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('in_progress', 'Devam Ediyor'), ('done', 'Tamamlandı')], default='pending', max_length=20),
        ),
    ]
