# Generated by Django 5.1.6 on 2025-04-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_rename_author_comment_user_alter_comment_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
